/// A plain-language explanation of a single accounting concept.
///
/// Content is static and rule-based (never generated by AI). Each concept is
/// identified by a stable [id] that both the "What does this mean?" help and
/// the first-time contextual tips reference.
class ConceptHelp {
  const ConceptHelp({
    required this.id,
    required this.title,
    required this.body,
  });

  final String id;
  final String title;
  final String body;
}

/// Stable identifiers for the built-in concepts.
abstract final class ConceptIds {
  ConceptIds._();

  static const invoice = 'invoice';
  static const receivable = 'receivable';
  static const profit = 'profit';
  static const payment = 'payment';
  static const bankReconciliation = 'bank_reconciliation';

  static const all = [
    invoice,
    receivable,
    profit,
    payment,
    bankReconciliation,
  ];
}
